### ISSUE TITLE
colorscheme

### ISSUE THREAD

**Issue by ghost** [SharkBaitOS/shark-bait.org#2]
We need a colorscheme.

Gentoo uses Tyrian,

https://github.com/gentoo/tyrian

Purple is cool with me but I'm fine with whatever.

**Comment by lramage94** [comment]
Gentoo Colors,
```
@gentoo-purple:           #54487A;
@gentoo-purple-light:     #61538D;
@gentoo-purple-light2:    #6E56AF;
@gentoo-purple-grey:      #DDDAEC;
@gentoo-green:            #73D216;
```
https://github.com/gentoo/tyrian/blob/v1/sources/css/tyrian/bootstrap/variables-tyrian.less

**Comment by oxr463** [comment]
I'm pretty sure we can close this now.
