### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ghost** [SharkBaitOS/shark-bait.org#3]
https://wiki.gentoo.org/wiki/Project:Artwork/Artwork

Fitting with, or at least alluding to Gentoo's branding could be good.
![Gentoo Logo](https://upload.wikimedia.org/wikipedia/commons/4/48/Gentoo_Linux_logo_matte.svg)

Turn the Gentoo logo into a shark/fish somehow?

Story behind name:
https://xkcd.com/349/

- Minimalist modern

PostMarketOS
![postmarketos](https://upload.wikimedia.org/wikipedia/commons/2/2d/Copperhead_logo.svg)

CopperheadOS
![CopperheadOS](https://upload.wikimedia.org/wikipedia/commons/a/a6/PostmarketOS_logo.svg)

- Anchor

![shark w/ anchor](http://www.etattoos.biz/upload/foto/0/sharkwithanchor.jpg)

![Anchor](http://4.bp.blogspot.com/-x8azXZdVxj0/UBE8wxNOflI/AAAAAAAAGfM/uDi_U-zID1k/s1600/beautifull-little-big-anchor-cute-tattoo-nice-anchor-tattoo-design-photos%2B%2B(11).jpg)

[Minimal sci-fi](https://www.youtube.com/watch?v=fTX0AbXlAHs)

- Captain's Wheel

![Photo](https://images-na.ssl-images-amazon.com/images/I/5123hC6LVML._SL500_AC_SS350_.jpg)

![Illustration](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ft3.ftcdn.net%2Fjpg%2F00%2F66%2F72%2F54%2F500_F_66725416_ZLobktDLomzFGZfifAexk4swJNSJSfhs.jpg&f=1)

- Life Saver

Used already by the KDE help center
Could have a bite taken out of it.
![Life Saver](http://www.backgroundsy.com/file/large/lifebuoy-life-saver.jpg)

- Sharks

![blue shark](http://kidzone.ws/sharks/photos/imgFE.jpg)
![thresher shark](http://kidzone.ws/sharks/photos/img109.jpg)

- Fish

Luvdisc looks like the Gentoo logo
![Luvdisc](https://vignette.wikia.nocookie.net/pokemon/images/9/91/370Luvdisc_AG_anime_2.png/revision/latest?cb=20150102000119)

- Mascot

http://tysontan.deviantart.com/

![Konqi](https://community.kde.org/images.community/thumb/9/99/Mascot_konqi-app-hardware.png/400px-Mascot_konqi-app-hardware.png)

![shark costume](https://ae01.alicdn.com/kf/HTB1sa65HVXXXXaVXpXXq6xXFXXX5/Cute-Shark-fish-Mascot-Costume-With-Funny-Eyes-For-Adult-Free-Shipping.jpg)

**Comment by UnderSampled** [comment]
Would you like to meet on IRC to discuss?
________________________________

**Comment by lramage94** [comment]
I'm on now and probably for the rest of the day

**Comment by oxr463** [comment]
This can also be closed.
